import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import { GetStaticProps } from 'next';
import { useTranslation } from 'next-i18next';
import { Header } from 'components';

export default function Home() {
  const { t } = useTranslation('home');

  return (
    <div>
      <Head>
        <title>Next.js TypeScript Boilerplate</title>
        <meta name="description" content="Generated by hand" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h1 className="mt-16 text-2xl text-center">{t('welcome')}</h1>
      </main>
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale!, ['common', 'home'])),
    },
  };
};
