import { Header } from 'components';
import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next.js TypeScript Boilerplate</title>
        <meta name="description" content="Generated by hand" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <h1 className="title">Welcome to Next.js TypeScript Boilerplate</h1>
      </main>

      <footer className="footer"></footer>
    </div>
  );
}
